---
#######################################
### Software Installation #############
#######################################

- hosts: db_servers:!centos
  tasks:
  - name: install mysql on Debian based servers
    apt:
      name: mysql-server
      update_cache: yes
      state: present
    become: true

- hosts: db_servers:!ubuntu
  tasks:
  - name: Install mysql on RHEL based servers
    yum:
      name: mysql-server
      state: present
    become: true

#######################################
### Service Management ################
#######################################

- hosts: db_servers:!centos
  tasks:
  - name: start mysql on Debian based servers
    service:
      name: mysql
      state: started
    become: true

- hosts: db_servers:!ubuntu
  tasks:
  - name: start mysql on RHEL based servers
    service:
      name: mysqld
      state: started
    become: true

#######################################
### Database Management ###############
#######################################

- hosts: db_servers:!centos
  tasks:
  - name: Install pip
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - python-pip
      - python-dev
      - libmysqlclient-dev
    become: true

  - name: install mysqldb via pip
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
      - pip
      - MySQL-python
    become: true

- hosts: db_servers
  tasks:
  - name: Configuring MySQL database - confluence
    mysql_db:
      name: confluence
      state: present
    become: true

  - name: Configuring MySQL user - confluence_user
    mysql_user:
      name: 'confluence_user'
      password: 'change_me_later'
      priv: 'confluence.*:ALL,GRANT'
    become: true
