---
#######################################
### Software Upgrades #################
#######################################

- include: patching.yaml

#######################################
### Software Installation #############
#######################################

- include: nginx.yaml

- include: mysql.yaml

