- name: Install Prereqs | Patching Server
  apt:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install Prereqs | Install aptitude (because apt-get does not like the next packages)
  apt:
    name: aptitude
    update_cache: yes
    state: present
  become: true

- name: Install Prereqs | Install tools
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - 'mysql-client'
    - 'nginx'
    - 'python-pip'
    - 'python-dev'
    - 'libmysqlclient-dev'
    - 'nmap'
    - 'traceroute'
    - 'tree'
    - 'atop'
    - 'lsof'
    - 'unzip'
  become: true

- name: install mysqldb via pip (For controlling DB Resources via Ansible)
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - MySQL-python
  become: true
